### PR TITLE
feat: Implement (partial) translation from Metal to Wasm

### PR DESCRIPTION
**Pull request by elenakrittik**

### CODE REVIEW

**Comment by elenakrittik** [comment]
* **#38** <a href="https://app.graphite.dev/github/pr/metallang/metal/38?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @elenakrittik and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by VincentRPS — CHANGES_REQUESTED** [review]
Should try to migrate to the MIR instead of the AST

**Comment by elenakrittik** [comment]
Don't see a reason for now. Also, the MIR doesn't yet support constants which are used here

**Review by VincentRPS — APPROVED** [review]
LGTM. Moving to MIR can be in another PR once constants are all set.

**Pull request merged**
