### PR TITLE
Metal Open Source

### LINKED ISSUE #65: License Under MIT
Put Metal into the permissive MIT license, which allows us to keep our attribution
while giving users lots of freedom with their compiled software and the compiler.

## Languages Using MIT

- Zig
- Rust (Dual under Apache-2.0)
- NodeJS
- Lua
- Nim
- Crystal
- ...

The only problem is there may be some problems, like with patent rights, which can be
prevented by using:

## Apache

We can also used Apache-2.0 with LLVM Exceptions used by LLVM and
a similar version of it is also used by Swift.

# Personal Conclusion

Personally, I think MIT would be fine. I doubt we're gonna be patenting anything, and
if anyone is contributing code I'd guess we'd already be checking whether or not
there's any patents that may be violated, such with all the other languages using MIT.

### PR DESCRIPTION
**Pull request by VincentRPS**
Places Metal under the permissive MIT license. Closes #65

### CODE REVIEW

**Review by elenakrittik — CHANGES_REQUESTED** [review]
The README needs changes. My proposal:

```md
## Contributing

As an open source project, we welcome contributions! However, because the project is still in it's early days,
the development is rather turbulent. For that reason, we suggest you to first let us know of your intentions by
opening an issue, or [joining our Discord](link) and saying "hello" there. Thanks!

```

**Review by elenakrittik — COMMENTED** [review]
Do we *really*, like, ***REALLY*** need license headers in every file?

**Comment by VincentRPS** [comment]
> Do we _really_, like, _**REALLY**_ need license headers in every file?

it's just better legally since it's harder to excuse not putting attribution for using our code,
especially when it's at the top of the file.

**Comment by elenakrittik** [comment]
As per discussion on Discord, [this SO post](https://softwareengineering.stackexchange.com/questions/125836/do-you-have-to-include-a-license-notice-with-every-source-file) (a "highly" "reliable" source, but that's the best we can get) and [this answer](https://softwareengineering.stackexchange.com/a/381907/434293) in particular, i have replaced the copyright notices with SPDX license identifiers.

Additionally, i have updated the main LICENSE file using the [SPDX](https://spdx.org/licenses/MIT.html) text of it. Following the lead of Facebook ([example](https://github.com/facebook/react/blob/main/LICENSE)), Microsoft ([example](https://github.com/microsoft/pyright/blob/main/LICENSE.txt), [example](https://github.com/dotnet/runtime/blob/main/LICENSE.TXT), [comment by a developer](https://github.com/microsoft/dotnet/issues/181)), Node.js ([example](https://github.com/nodejs/node/blob/main/LICENSE)), and somewhat Rust ([commit-discussion](https://github.com/rust-lang/rust/commit/2a8807e889a43c6b89eb6f2736907afa87ae592f)), i didn't add the copyright date. Following the lead of Node.js (see previously linked example), libuv ([example](https://github.com/libuv/libuv/blob/v1.x/LICENSE)), and Vue ([example](https://github.com/vuejs/core/blob/main/LICENSE)), i left the "Metal contributors" part as is.

Note that the point of these example is not to show that "this is how most projects do it". In fact, directly below this paragraph i complain about the opposite. The point is to show that *some* major/popular projects do it this way, and therefore doing this way is a viable option.

As an aside, i hate how much of a gray area all of this open source licensing is. You can google a question, wait a month, google it again, and get totally different answers. Even if you only look at the "big" projects, that are *supposed* to actually care about copyright and stuff, there's no coherence there, at all.

Some projects have `start year`, some `start year - end year`, some `start year, all years in-between, end year`, some `start year - present`, some just omit the date entirely.

Some projects have a legal entity name as an author, some have authors' real names, some keep an AUTHORS file, some specify username, some say "<project blah> contributors", some *omit it* (???).

The need of duplicating copyright notices in all project files is also debated. Some projects copy the license fully, some refer to the "project root" or "LICENSE" file (which may not even exist by the time the code is copied), some just specify what license is used, some, again, omit this entirely. Here at least there is *some* effort going on to standardize this mess (namely, SPDX).

**Comment by elenakrittik** [comment]
And finally, the mandatory disclaimer: I agree to license all of my past contributions to this project, available at https://github.com/metallang/metal, under the MIT license as available at https://spdx.org/licenses/MIT.html

(all future contributions will be automatically licensed thanks to GitHub's explicit inbound=outbound policy)

**Comment by elenakrittik** [comment]
I will approve the PR once you do the same

**Comment by VincentRPS** [comment]
I agree to license all of my past contributions to this project, available at https://github.com/metallang/metal, under the MIT license as available at https://spdx.org/licenses/MIT.html

(all future contributions will be automatically licensed thanks to GitHub's explicit inbound=outbound policy)

**Pull request merged**
